apiVersion: v1
data:
  BG_COLOR: green
kind: ConfigMap
metadata:
  name: app-config-g8ck4h8m8g
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo1
  name: demo1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo1
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo1
  name: demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: app-config-g8ck4h8m8g
        image: ghcr.io/gattma/demo1:main-00f4a2d
        name: demo1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
