apiVersion: v1
data:
  BG_COLOR: red
kind: ConfigMap
metadata:
  name: app-config-747h552fg4
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo2
  name: demo2
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo2
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo2
  name: demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo2
  template:
    metadata:
      labels:
        app: demo2
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: app-config-747h552fg4
        image: ghcr.io/gattma/demo2:main-00f4a2d
        name: demo2
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
