apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo1
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: app-config-g8ck4h8m8g
        image: {{ .Values.image }}
        name: demo1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
