apiVersion: apps/v1
kind: Deployment
metadata:
  name: silly-demo
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: silly-demo
        image: ghcr.io/gattma/silly-demo:main-00f4a2d
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
